name: Build
on:
  pull_request:
    branches: [main]

jobs:
  check-setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - name: Check setup.py is valid
        run: |
          python setup_check.py
