name: Lint
on:
  pull_request:
    branches: [main]

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: psf/black@22.6.0
        with:
          options: "--line-length 120 --check --diff cfdibills tests"
  isort:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: jamescurtin/isort-action@master
        with:
          configuration: "--profile black --filter-files --check-only --diff cfdibills tests"
          requirementsFiles: "requirements.txt requirements_test.txt"
  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: jpetrucciani/mypy-check@0.930
        with:
          mypy_flags: "--ignore-missing-imports --pretty --non-interactive --install-types"
          path: "cfdibills tests"
  flake8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: flake8 (*.py)
        uses: py-actions/flake8@v2
        with:
          ignore: "E731,W503,W504"
          exclude: "__init__.py"
          max-line-length: "120"
          args: "--show-source --statistics --filename=*.py cfdibills/ tests/"
      - name: flake8 (__init__.py)
        uses: py-actions/flake8@v2
        with:
          ignore: "E731,F401,F403,W503"
          max-line-length: "120"
          args: "--show-source --statistics --filename=*__init__.py cfdibills/ tests/"

