name: Requirements
on:
  pull_request:
    branches: [main]

jobs:
  are-compiled:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_dev.txt
      - name: Check requirements.in is compiled
        run: |
          pip-compile -q requirements.in && git diff --exit-code -- requirements.txt
